name: 'Create PR to other branches, on commits to a branch'
description: 'Commits, pushes a new PR branch and creates PR for the commits.'
author: '@himadrisingh'
inputs:
  pr_branch:
    description: 'Target Branch to create PR'
    required: true
  pr_labels:
    description: 'Labels for the new PR'
    required: false
    default: 'autocreated'
  allow_merges:
    description: 'Allow merge SHAs to be cherry_picked'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: git-merge
  color: yellow
